### ISSUE TITLE
Make it better by...

### ISSUE THREAD

**Issue by notenociz** [eduardo-costa/shortcutcss#2]
The main CSS file can be made a lot smaller and better.

Would you agree with the following?

Proposed changes:
- Make all units responsive when seen fit
  - This means the widths, heights, font sizes and other declarations should be vh, vw, rem, em or %.
  - Don't change to responsive units for things like border sizes etc.
- Remove unnecessary classes
  - Such as the many sizes for heights etc. instead, only include them in increments or in commonly used values

If I find any more, I'll include them. What do you think of the above?

**Comment by eduardo-costa** [comment]
Didn't get 100%.
- Give an example how the units should be declared
- Which classes exactly we should use increments?
  -  For instance "relative font-size" `.rfs`goes from 0.01 to 4.00 with 0.01 increments (we can go with 0.02 increments)

**Comment by notenociz** [comment]
Sorry for not making myself clear

---

An example of how the units should be declared: ok. Let's take width. Instead of saying

``` css

.w16 { width: 16px; }
.w32 { width: 32px; }
.w64 { width: 64px; }
.w128 { width: 128px; }

```

you would do

``` css

.w1 { width: 1em; }
.w2 { width: 2em; }
.w3 { width: 4em; }
.w4 { width: 8em; }

```

and would also add

``` css

.w-full { width: 100%; }
.w-half { width: 50%; }
.w-quarter { width: 25%; }
.w-eight { width: 12.5%; }

```

to it (naming it better than what I have done there of course).

---

You should use increments for all classes if possible and add in any values which are not covered by the increment scale but you would use regularly.

I would recommend that you look at [Tachyons by mrmrs](https://github.com/mrmrs/tachyons). I do not exactly like the naming styles there but it still shows my point. It is very light, uses responsive units and doesn't have unwanted things in a 1 step scale. It uses increments of ^2 (2, 4, 8, 16 etc.).

I would recommend increments of ^2 because it cuts out unnecessary values. If you use any other values (such as let's say widths of 5%, 10% or 100%), add them in as well.
